### ISSUE TITLE
onJoin callback not executing

### ISSUE THREAD

**Issue by emberlightstudios** [icefo/PyQt5-Wamp#2]
I can't get this to work to subscribe to a push API online.  onJoin never fires even though I am inheriting from ApplicationSession.   It's weird because onConnect and onDisconnect both work as expected.

**Comment by icefo** [comment]
Maybe you forgot to add the the decorator to the onJoin function ?

I have my finals coming but if you show me your code I can take a quick look.

**Comment by emberlightstudios** [comment]
I changed it to the new style but I tried with the old decorator also.  Same result.

    from qtpy.QtWidgets import *
    from sys import argv
    from push import *
    from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner
    from quamash import QEventLoop
    import logging
    import asyncio
    
    
    class AppWindow(ApplicationSession, QMainWindow):
    
        def __init__(self, config=None):
            ApplicationSession.__init__(self, config=config)
            QMainWindow.__init__(self)
    
            self.statusBar()
            self.show()
    
        async def onJoin(self, details):
            logging.info('joined')
            await self.subscribe(on_troll, 'trollbox')
    
        def onDisconnect(self):
            self.statusBar().showMessage('Connection lost.')
    
        def onConnect(self):
            self.statusBar().showMessage('Connected.')
    
    
    def main():
        logging.basicConfig(format='[%(asctime)s] %(message)s',
                            datefmt="%H:%M:%S", level=logging.INFO)
        app = QApplication(argv)
        asyncio_loop = QEventLoop(app)
        asyncio.set_event_loop(asyncio_loop)
        runner = ApplicationRunner(u"wss://api.poloniex.com:443", u"realm1")
        logging.info('Starting the runner')
        runner.run(AppWindow)
    
    if __name__ == "__main__":
        main()

I'm also getting this error when closing the application, might be related:
autobahn.wamp.exception.SessionNotReady: session hasn't joined a realm

Although it works fine without Qt.

**Comment by icefo** [comment]
I just saw you are using qtpy instead of pyqt5. This may be the cause of your problem.

If you're on Linux pyqt5 is installable using your package manager.

**Comment by emberlightstudios** [comment]
No, unfortunately using PyQt5 didn't change anything.  It's just an abstraction layer so I wouldn't think it would make a difference since it just loads the PyQt5 modules anyway.

**Comment by icefo** [comment]
It's weird I didn't see anything wrong in your code but I have not touched that in a year.

I advise you to try to make the example work (you should not have to change anything) and see where it breaks when you change it.

I'm won't have time to really look into it until Wednesday

**Comment by icefo** [comment]
Did you manage to get the example code running ?

I updated the project a bit and I know it works on python 3.5 and should on python 3.4 too

**Comment by emberlightstudios** [comment]
I have kind of given up after a while of just being frustrated.   I think maybe Qt is not the way to go anyway.  Thanks for your help,

**Comment by icefo** [comment]
This will stay a mystery then. Good luck with your project !
